<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="U5-DPE-CPB-0221" failures="0" tests="4" name="servicetester.test.Driver" time="3.041" errors="1" timestamp="26 Apr 2019 06:07:31 GMT" skipped="0">
  <testcase classname="servicetester.test.Driver" name="validate_all_responce_from_request" time="2.623"/>
  <testcase classname="servicetester.test.Driver" name="compare_responce_expected_with_actual_soapresponce_first" time="0.290"/>
  <testcase classname="servicetester.test.Driver" name="check_namespace_is_proper_soapresponce_first" time="0.039">
    <error message="Unresolved compilation problem: 
	Duplicate local variable fis
" type="java.lang.Error">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
Duplicate local variable fis

at servicetester.test.Driver.check_namespace_is_proper_soapresponce_first(Driver.java:124)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- check_namespace_is_proper_soapresponce_first -->
  <testcase classname="servicetester.test.Driver" name="validate_expect_actual_soapresponce_first" time="0.089"/>
</testsuite> <!-- servicetester.test.Driver -->
